trigger:
  batch: true
  branches:
    include:
      - dev

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: environment
    value: dev
  - template: templates/variables.yaml

stages:
  - template: templates/workflow.yaml
