trigger:
  branches:
    include:
      - dev

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: templates/variables.yaml
  - name: environment
    value: dev

stages:
  - stage: CreateConfig
    displayName: Create/update K8s configuration resources
    jobs:
      - template: templates/create-config.yaml

  - stage: DeployPrerequisites
    displayName: Deploy Datahub Prerequisites
    jobs:
      - template: templates/deploy-prereq.yaml

  - stage: DeployDatahub
    displayName: Deploy Datahub
    jobs:
      - template: templates/deploy-datahub.yaml

  - stage: CreateIngress
    displayName: Create/update K8s ingress resource
    jobs:
      - template: templates/create-ingress.yaml
