trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  kubernetesServiceConnection: Datahub-DEV-uni-apps-aks-dev-ictd-oi-datahub-dev-1684231863813
  kubernetesNamespace: ictd-oi-datahub-dev

steps:
- task: HelmDeploy@0
  displayName: 'Add Datahub Helm Repo'
  enabled: true
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: 'repo'
    arguments: 'add datahub https://helm.datahubproject.io/'
    namespace: $(kubernetesNamespace)

- task: HelmDeploy@0
  displayName: 'Add Deploy Datahub Prerequisites'
  enabled: true
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: 'install'
    arguments: 'prerequisites datahub/datahub-prerequisites'
    namespace: $(kubernetesNamespace)



- task: HelmDeploy@0
  displayName: Helm deploy Datahub
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: install
    chartType: Name
    chartName: datahub/datahub
    releaseName: datahub
    namespace: $(kubernetesNamespace)

#- task: Kubernetes@1
#  displayName: Set up Ingress
#  inputs:
#    connectionType: Kubernetes Service Connection
#    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
#    command: apply
#    arguments: '-f azure/ingress.yaml'
#    namespace: $(kubernetesNamespace)
