trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: templates/variables.yaml

stages:
  - stage: Uninstall
    displayName: Uninstall Datahub Helm charts
    jobs:
      - template: templates/helm-uninstall.yaml

  - stage: Delete
    displayName: Delete Datahub K8s resources
    jobs:
      - template: templates/delete-resources.yaml
