trigger:
- dev

pool:
  vmImage: ubuntu-latest

variables:
  kubernetesNamespace: $(DATAHUB_NAMESPACE)
  secretsVaultName: $(SECRETS_VAULT_NAME)
  aksSecretsName: $(AKS_SECRETS_NAME)
  system.debug: true

steps:
- task: Bash@3
  displayName: Run Secrets Sync Script
  inputs:
    filePath: secretsSync.sh
    arguments: "$secretsVaultName $kubernetesNamespace $aksSecretsName"
