# Notes:
#
# First match wins
#
# queryRegex = Java regex syntax
#
# functionScores - See the following for function score syntax
# https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-function-score-query.html

x-function-boost-delta-lake: &boostDeltaLake
  filter:
    term:
      platform.keyword:
        - urn:li:dataPlatform:deltaLake
  weight: 3.0

x-bury-deprecated: &buryDeprecated
  must_not:
    term:
      deprecated:
        value: true

queryConfigurations:
  # Select *
  - queryRegex: '[*]|'
    simpleQuery: false
    prefixMatchQuery: false
    exactMatchQuery: false
    boolQuery:
      <<: *buryDeprecated
    functionScore:
      functions:
        - filter:
            term:
              materialized:
                value: true
          weight: 0.8
        - <<: *boostDeltaLake
      score_mode: multiply
      boost_mode: multiply

  # Criteria for exact-match only
  # Contains quoted then use exact match query
  - queryRegex: >-
      ["'].+["']
    simpleQuery: false
    prefixMatchQuery: true
    exactMatchQuery: true
    functionScore:
      functions:
        - filter:
            term:
              materialized:
                value: true
          weight: 0.8
        - filter:
            term:
              deprecated:
                value: true
          weight: 0
      score_mode: multiply
      boost_mode: multiply

  # default
  - queryRegex: .*
    simpleQuery: true
    prefixMatchQuery: true
    exactMatchQuery: true
    boolQuery:
      <<: *buryDeprecated
    functionScore:
      functions:
        - filter:
            term:
              materialized:
                value: true
          weight: 0.8
        - <<: *boostDeltaLake
      score_mode: multiply
      boost_mode: multiply
