version: '3'

dotenv:
  - .env

vars:
  PROJECT_NAME: giga-dataops_datahub
  SHORT_SHA:
    sh: git rev-parse --short HEAD
  DATAHUB_VERSION: 0.11.0

tasks:
  default:
    cmds:
      - task: up

  up:
    desc: Build and start Docker containers
    cmds:
      - docker compose --project-name giga-dataops-platform --file docker-compose-network.yaml up --detach --build --remove-orphans {{.CLI_ARGS}}
      - docker compose --project-name {{.PROJECT_NAME}} up --detach --build --remove-orphans {{.CLI_ARGS}}

  setup:
    desc: Run initial setup
    cmds:
      - helm repo add datahub https://helm.datahubproject.io

  logs:
    desc: Attach to Docker logs
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} stop {{.CLI_ARGS}}

  restart:
    desc: Restart containers
    cmds:
      - task: generate-dagster-yaml
      - docker compose --project-name {{.PROJECT_NAME}} restart {{.CLI_ARGS}}

  exec:
    desc: Run a command in the specified container
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} exec {{.CLI_ARGS}}

  ps:
    desc: Show running processes in this project
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} ps

  clean:
    desc: Remove containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} down --volumes --remove-orphans {{.CLI_ARGS}}
      - docker compose --project-name giga-dataops-platform --file docker-compose-network.yaml down --volumes --remove-orphans {{.CLI_ARGS}}

  helm-up:
    desc: Install/upgrade Datahub Helm chart on a local cluster
    dir: helm
    cmds:
      - task: k8s-prereqs
      - task: helm-up-prereqs
      - task: helm-up-datahub

  helm-upi:
    desc: Install/upgrade Datahub Helm chart with HTTPS ingress
    dir: helm
    cmds:
      - task: k8s-prereqs
      - task: helm-up-prereqs
      - task: helm-up-datahub

  k8s-prereqs:
    internal: true
    desc: Install K8s configs/secrets
    dir: k8s
    cmds:
      - kubectl apply -f namespace.yaml
      - kubectl apply -f secrets.yaml --namespace giga-datahub
      - kubectl apply -f configmap.yaml --namespace giga-datahub

  helm-up-prereqs:
    desc: Install/upgrade Datahub prerequisites
    dir: helm
    cmds:
      - >
        helm upgrade --install prerequisites datahub/datahub-prerequisites
        --version 0.1.8
        --values prerequisites-values.yaml
        --values prerequisites-values-local-override.yaml
        --values prerequisites-values-prd-override.yaml
        --namespace giga-datahub
        --create-namespace
        --set postgresql.primary.readinessProbe.enabled=false
        --set postgresql.primary.livenessProbe.enabled=false
        --set elasticsearch.ingress.hosts[0].host={{.DATAHUB_ES_INGRESS_HOST}}

  helm-up-datahub:
    desc: Install/upgrade Datahub
    dir: helm
    cmds:
      - >
        helm upgrade --install datahub datahub/datahub
        --version 0.4.0
        --values values.yaml
        --values values-override-dev-stg.yaml
        --namespace giga-datahub
        --create-namespace
        --timeout 1h
        --set datahub-frontend.ingress.hosts[0].host={{.AUTH_OIDC_BASE_URL}}
        --set datahub-frontend.ingress.annotations=null
        --set datahub-frontend.oidcAuthentication.clientSecretRef.secretRef=giga-datahub-secrets
        --set datahub-frontend.oidcAuthentication.azureTenantId={{.AUTH_OIDC_TENANT_ID}}
        --set datahub-frontend.extraEnvs[0].valueFrom.secretKeyRef.name=giga-datahub-secrets
        --set datahub-gms.ingress.enabled=true
        --set datahub-gms.ingress.hosts[0].host={{.DATAHUB_GMS_INGRESS_HOST}}
        --set datahub-gms.ingress.hosts[0].paths[0]=/

  helm-down:
    desc: Uninstall Helm charts
    ignore_error: true
    dir: k8s
    cmds:
      - helm uninstall datahub --namespace giga-datahub
      - helm uninstall prerequisites --namespace giga-datahub

  helm-clean:
    desc: Cleanup K8s resources
    ignore_error: true
    dir: k8s
    cmds:
      - kubectl delete all --all --namespace giga-datahub
      - kubectl delete pvc --all --namespace giga-datahub
      - kubectl delete -f namespace.yaml
