version: '3'

dotenv:
  - .env

vars:
  PROJECT_NAME: giga-dataops_datahub
  SHORT_SHA:
    sh: git rev-parse --short HEAD
  DATAHUB_VERSION: 0.11.0

tasks:
  default:
    cmds:
      - task: up

  up:
    desc: Build and start Docker containers
    cmds:
      - docker compose --project-name giga-dataops-platform --file docker-compose-network.yaml up --detach --build --remove-orphans {{.CLI_ARGS}}
      - docker compose --project-name {{.PROJECT_NAME}} up --detach --build --remove-orphans {{.CLI_ARGS}}

  setup:
    desc: Run initial setup
    cmds:
      - helm repo add datahub https://helm.datahubproject.io

  logs:
    desc: Attach to Docker logs
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} stop {{.CLI_ARGS}}

  restart:
    desc: Restart containers
    cmds:
      - task: generate-dagster-yaml
      - docker compose --project-name {{.PROJECT_NAME}} restart {{.CLI_ARGS}}

  exec:
    desc: Run a command in the specified container
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} exec {{.CLI_ARGS}}

  ps:
    desc: Show running processes in this project
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} ps

  clean:
    desc: Remove containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} down --volumes --remove-orphans {{.CLI_ARGS}}
      - docker compose --project-name giga-dataops-platform --file docker-compose-network.yaml down --volumes --remove-orphans {{.CLI_ARGS}}

  helm-up:
    desc: Install/upgrade Datahub Helm chart on a local cluster
    dir: helm
    cmds:
      - task: k8s-prereqs
      - task: helm-up-prereqs
      - task: helm-up-datahub

  helm-upi:
    desc: Install/upgrade Datahub Helm chart with HTTPS ingress
    dir: helm
    cmds:
      - task: k8s-prereqs
      - task: helm-up-prereqs
      - task: helm-up-datahub
      - task: k8s-ingress

  k8s-prereqs:
    internal: true
    desc: Install K8s configs/secrets
    dir: k8s
    cmds:
      - kubectl apply -f namespace.yaml
      - kubectl apply -f secrets.yaml --namespace giga-datahub

  k8s-ingress:
    internal: true
    desc: Install k8s ingress
    dir: k8s
    cmds:
      - kubectl apply -f ingress-local.yaml --namespace giga-datahub

  helm-up-prereqs:
    internal: true
    desc: Install/upgrade Datahub prerequisites
    dir: helm
    cmds:
      - >
        helm upgrade --install prerequisites datahub/datahub-prerequisites
        --values prerequisites-values.yaml
        --namespace giga-datahub
        --create-namespace

  helm-up-datahub:
    internal: true
    desc: Install/upgrade Datahub
    dir: helm
    cmds:
      - >
        helm upgrade --install datahub ./datahub
        --values values.yaml
        --namespace giga-datahub
        --create-namespace
        --timeout 1h
        --set datahub-frontend.ingress.hosts[0].host={{.AUTH_OIDC_BASE_URL}}
        --set datahub-frontend.oidcAuthentication.provider=google
        --set datahub-frontend.oidcAuthentication.clientIdRef.secretRef=giga-datahub
        --set datahub-frontend.oidcAuthentication.clientIdRef.secretKey=AUTH_OIDC_CLIENT_ID
        --set datahub-frontend.oidcAuthentication.clientSecretRef.secretRef=giga-datahub
        --set datahub-frontend.oidcAuthentication.clientSecretRef.secretKey=AUTH_OIDC_CLIENT_SECRET

  #        --set datahub-frontend.oidcAuthentication.azureTenantId={{.AUTH_OIDC_TENANT_ID}}

  helm-down:
    desc: Uninstall Helm charts
    ignore_error: true
    dir: k8s
    cmds:
      - helm uninstall datahub --namespace giga-datahub
      - helm uninstall prerequisites --namespace giga-datahub
      - kubectl delete all --all --namespace giga-datahub
      - kubectl delete pvc --all --namespace giga-datahub
      - kubectl delete -f namespace.yaml
