apiVersion: v1
kind: ConfigMap
metadata:
  name: giga-datahub-configmap
data:
  custom_search_config.yml: |
    queryConfigurations:
      - queryRegex: .*
        simpleQuery: true
        prefixMatchQuery: true
        exactMatchQuery: true
        functionScore:
          functions:
            - filter:
                term:
                  deprecated:
                    value: true
              weight: 0.01
            - filter:
                terms:
                  platform.keyword:
                    - urn:li:dataPlatform:deltaLake
              weight: 5.0
            - filter:
                bool:
                  should:
                    - match:
                        id.keyword: school_master.db
              weight: 10.0
            - filter:
                bool:
                  should:
                    - regexp:
                        id.keyword: '.*dq[-_]results.*'
              weight: 0.1
            - filter:
                bool:
                  should:
                    - match:
                        urn.keyword: urn:li:corpuser
                    - match:
                        urn.keyword: urn:li:corpgroup
              weight: 0.05
          score_mode: multiply
          boost_mode: multiply
