apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  labels:
    name: postgresql-secrets
    app: giga-datahub
stringData:
  postgres-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secrets
  labels:
    name: neo4j-secrets
    app: giga-datahub
stringData:
  neo4j-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: datahub-users-secret
  labels:
    name: datahub-users-secret
    app: giga-datahub
stringData:
  user.props: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: giga-datahub
  labels:
    app: giga-datahub
stringData:
  AUTH_OIDC_CLIENT_ID: ""
  AUTH_OIDC_CLIENT_SECRET: ""
