jobs:
  - deployment: Deploy
    displayName: Create/update GMS ingress resource
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Kubernetes@1
              displayName: Set up Datahub GMS ingress
              inputs:
                namespace: $(kubernetesNamespace)
                command: apply
                useConfigurationFile: true
                configuration: k8s/gms-ingress.yaml
