jobs:
  - deployment: Deploy
    displayName: Create/update GMS ingress resource
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Kubernetes@1
              displayName: Set up Datahub GMS ingress
              condition: eq(variables.DEPLOY_ENV, 'dev')
              inputs:
                namespace: $(kubernetesNamespace)
                command: apply
                useConfigurationFile: true
                configuration: k8s/gms-ingress.yaml

            - task: Kubernetes@1
              displayName: Delete old ingress
              inputs:
                command: delete
                arguments: ingress giga-datahub-ingress --ignore-not-found
                namespace: $(kubernetesNamespace)
