jobs:
  - deployment: Deploy
    displayName: Deploy Datahub Prerequisites
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Add Datahub Helm Repo
              inputs:
                command: repo
                arguments: add datahub https://helm.datahubproject.io/
                namespace: $(kubernetesNamespace)

            - task: HelmDeploy@0
              displayName: Deploy Datahub Prerequisites
              enabled: true
              continueOnError: true
              inputs:
                command: upgrade
                chartType: Name
                chartName: datahub/datahub-prerequisites
                chartVersion: 0.1.8
                releaseName: prerequisites
                namespace: $(kubernetesNamespace)
                valueFile: helm/prerequisites-values.yaml
