jobs:
  - deployment: Deploy
    displayName: Deploy Datahub Prerequisites
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Add Datahub Helm Repo
              inputs:
                command: repo
                arguments: add datahub https://helm.datahubproject.io/
                namespace: $(kubernetesNamespace)

            #            - task: Kubernetes@1
            #              displayName: Delete existing jobs
            #              inputs:
            #                command: delete
            #                namespace: $(kubernetesNamespace)
            #                arguments: job --all

            - task: HelmDeploy@0
              displayName: Deploy Datahub dev Prerequisites
              enabled: true
              condition: eq(variables.environment, 'dev')
              inputs:
                command: upgrade
                chartType: Name
                chartName: datahub/datahub-prerequisites
                chartVersion: 0.1.8
                releaseName: prerequisites
                namespace: $(kubernetesNamespace)
                valueFile: helm/prerequisites-values.yaml
                arguments: --values helm/prerequisites-values-dev-override.yaml

            - task: HelmDeploy@0
              displayName: Deploy Datahub stg/prd Prerequisites
              enabled: true
              condition: or(eq(variables.environment, 'stg'), eq(variables.environment, 'prd'))
              inputs:
                command: upgrade
                chartType: Name
                chartName: datahub/datahub-prerequisites
                chartVersion: 0.1.8
                releaseName: prerequisites
                namespace: $(kubernetesNamespace)
                valueFile: helm/prerequisites-values.yaml
                arguments: --values helm/prerequisites-values-prd-override.yaml
