jobs:
  - deployment: Deploy
    displayName: Deploy Datahub
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Add Datahub Helm Repo
              inputs:
                command: repo
                arguments: add datahub https://helm.datahubproject.io/
                namespace: $(kubernetesNamespace)

            - task: HelmDeploy@0
              displayName: Helm deploy Datahub
              condition: eq(variables.environment, 'dev')
              inputs:
                command: upgrade
                chartType: Name
                chartName: datahub/datahub
                chartVersion: 0.4.0
                releaseName: datahub
                valueFile: helm/values.yaml
                namespace: $(kubernetesNamespace)
                arguments: >
                  --timeout 1h
                  --set datahub-frontend.ingress.enabled=true
                  --set datahub-frontend.ingress.hosts[0].host="$(ingressHost)"

            - task: HelmDeploy@0
              displayName: Helm deploy staging-config Datahub
              # FIXME: Temporary workaround while Azure AD secrets are not provided yet
              condition: eq(variables.environment, 'stg')
              inputs:
                command: upgrade
                chartType: Name
                chartName: datahub/datahub
                chartVersion: 0.4.0
                releaseName: datahub
                valueFile: helm/values.yaml
                namespace: $(kubernetesNamespace)
                arguments: >
                  --timeout 1h
                  --set datahub-frontend.oidcAuthentication.provider=google
                  --set datahub-frontend.oidcAuthentication.clientIdRef.secretRef=giga-datahub-secrets
                  --set datahub-frontend.oidcAuthentication.clientIdRef.secretKey=AUTH_OIDC_CLIENT_ID
                  --set datahub-frontend.oidcAuthentication.clientSecretRef.secretRef=giga-datahub-secrets
                  --set datahub-frontend.oidcAuthentication.clientSecretRef.secretKey=AUTH_OIDC_CLIENT_SECRET
                  --set datahub-frontend.ingress.enabled=true
                  --set datahub-frontend.ingress.hosts[0].host="$(ingressHost)"

            - task: HelmDeploy@0
              displayName: Helm deploy production-config Datahub
              condition: eq(variables.environment, 'prd')
              inputs:
                command: upgrade
                chartType: Name
                chartName: datahub/datahub
                chartVersion: 0.4.0
                releaseName: datahub
                valueFile: helm/values.yaml
                namespace: $(kubernetesNamespace)
                arguments: >
                  --timeout 1h
                  --values helm/values-override-prd.yaml
                  --set datahub-frontend.ingress.enabled=true
                  --set datahub-frontend.ingress.hosts[0].host="$(ingressHost)"
                  --set datahub-frontend.extraEnvs[1].valueFrom.secretKeyRef.name=oi-datahub-secrets-$(deployEnv)
                  --set datahub-frontend.extraEnvs[2].valueFrom.secretKeyRef.name=oi-datahub-secrets-$(deployEnv)

            - task: Kubernetes@1
              displayName: Force restart Datahub frontend
              inputs:
                namespace: $(kubernetesNamespace)
                command: rollout
                arguments: restart deploy datahub-datahub-frontend
