jobs:
  - deployment: Deploy
    displayName: Deploy Datahub
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Add Datahub Helm Repo
              inputs:
                command: repo
                arguments: add datahub https://helm.datahubproject.io/
                namespace: $(kubernetesNamespace)

            - task: HelmDeploy@0
              displayName: Helm deploy Datahub dev
              # Uses Entra ID
              condition: eq(variables.environment, 'dev')
              inputs:
                command: upgrade
                chartType: Name
                chartName: datahub/datahub
                chartVersion: 0.4.0
                releaseName: datahub
                valueFile: helm/values.yaml
                namespace: $(kubernetesNamespace)
                arguments: >
                  --timeout 1h
                  --values helm/values-override-dev-stg.yaml
                  --values helm/values-override-stg-prd.yaml
                  --set datahub-frontend.ingress.hosts[0].host="$(ingressHost)"
                  --set datahub-frontend.oidcAuthentication.clientSecretRef.secretRef="oi-datahub-secrets-$(deployEnv)"
                  --set datahub-frontend.oidcAuthentication.azureTenantId="$(azureTenantId)"
                  --set datahub-frontend.extraEnvs[0].valueFrom.secretKeyRef.name="oi-datahub-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm deploy Datahub stg
              condition: eq(variables.environment, 'stg')
              inputs:
                command: upgrade
                chartType: Name
                chartName: datahub/datahub
                chartVersion: 0.4.0
                releaseName: datahub
                valueFile: helm/values.yaml
                namespace: $(kubernetesNamespace)
                arguments: >
                  --timeout 1h
                  --values helm/values-override-dev-stg.yaml
                  --values helm/values-override-stg-prd.yaml
                  --set datahub-frontend.ingress.hosts[0].host="$(ingressHost)"
                  --set datahub-frontend.oidcAuthentication.clientSecretRef.secretRef="giga-datahub-secrets"
                  --set datahub-frontend.oidcAuthentication.azureTenantId="$(azureTenantId)"
                  --set datahub-frontend.extraEnvs[0].valueFrom.secretKeyRef.name="giga-datahub-secrets"

            - task: HelmDeploy@0
              displayName: Helm deploy Datahub prd
              # Uses B2C
              condition: eq(variables.environment, 'prd')
              inputs:
                command: upgrade
                chartType: Name
                chartName: datahub/datahub
                chartVersion: 0.4.0
                releaseName: datahub
                valueFile: helm/values.yaml
                namespace: $(kubernetesNamespace)
                arguments: >
                  --timeout 1h
                  --values helm/values-override-prd.yaml
                  --values helm/values-override-stg-prd.yaml
                  --set datahub-frontend.ingress.hosts[0].host="$(ingressHost)"

#            - task: Kubernetes@1
#              displayName: Force restart deployments
#              inputs:
#                namespace: $(kubernetesNamespace)
#                command: rollout
#                arguments: restart deploy datahub-datahub-frontend datahub-datahub-gms
