jobs:
  - deployment: Deploy
    displayName: Uninstall all Helm charts
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - task: HelmDeploy@0
              displayName: Helm uninstall Datahub
              inputs:
                namespace: $(kubernetesNamespace)
                command: uninstall
                arguments: datahub

            - task: HelmDeploy@0
              displayName: Helm uninstall Datahub prerequisites
              inputs:
                namespace: $(kubernetesNamespace)
                command: uninstall
                arguments: prerequisites
