datahub-gms:
  replicaCount: 2

global:
  elasticsearch:
    host: elasticsearch-master-headless
  datahub_standalone_consumers_enabled: true  # Enable standalone mode to allow multiple GMS instances with managed ingestion
